name: 'Trigger Deployment'
description: 'Trigger a deployment of a service'
author: 'Peachjar Engineering'
inputs:
  token:
    required: true
    description: Github token used to create the deployment.
  environment:
    required: true
    description: The environment you want to deploy to.
  requiredContexts:
    required: false
    description: 'The build steps that should have passed (default: none)'
    default: ''
  description:
    required: false
    description: 'An optional description of why the deploy is being triggered'
    default: 'Deployed as a result of a code change'
  repository:
    required: false
    description: The github repository (owner/repo) that is being deployed
    default: ${{ github.repository }}
  ref:
    required: false
    description: The ref that this deployment is run on
    default: ${{ github.ref }}
  payload:
    required: false
    description: Additional metadata to include on the deployment
  autoMerge:
    required: false
    default: false
    description: Ensure that master merges cleanly into deploy (see Github Deployment API)
runs:
  using: 'node12'
  main: 'dist/index.js'
